# Ejemplos de temas integrados:
# theme: jekyll-theme-cayman
# theme: jekyll-theme-primer
# theme: jekyll-theme-slate
# theme: jekyll-theme-merlot
title: Memoria Dual
description: Memoria Dual de mi estada en Circutor S.A.U.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
