# Ejemplos de temas integrados:
# theme: jekyll-theme-cayman
# theme: jekyll-theme-primer
# theme: jekyll-theme-slate
# theme: jekyll-theme-merlot
# Tema elegido
theme: jekyll-theme-architect

# Texto que aparece en la cabecera azul
title: "Mi memoria dual en Circutor"
description: "Ismael Ferrón Clavero"

